const RegisterDateTime = [
  {
    did: 1,
    name_la: "ຈັນ",
    name_th: "",
    name_en: "",
    destiny: "",
  },
  {
    did: 2,
    name_la: "ຄານ",
    name_th: "",
    name_en: "",
    timeOp: "",
    timeClo: "",
    breakStart: "",
    breakEnd: "",
  },
  {
    did: 3,
    name_la: "ພຸດ",
    name_th: "",
    name_en: "",
    timeOp: "",
    timeClo: "",
    breakStart: "",
    breakEnd: "",
  },
  {
    did: 4,
    name_la: "ພະຫັດ",
    name_th: "",
    name_en: "",
    timeOp: "",
    timeClo: "",
    breakStart: "",
    breakEnd: "",
  },
  {
    did: 5,
    name_la: "ສຸກ",
    name_th: "",
    name_en: "",
    timeOp: "",
    timeClo: "",
    breakStart: "",
    breakEnd: "",
  },
  {
    did: 6,
    name_la: "ເສົາ",
    name_th: "",
    name_en: "",
    timeOp: "",
    timeClo: "",
    breakStart: "",
    breakEnd: "",
  },
  {
    did: 7,
    name_la: "ອາທິດ",
    name_th: "",
    name_en: "",
    timeOp: "",
    timeClo: "",
    breakStart: "",
    breakEnd: "",
  },
];

export default RegisterDateTime;
